// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source usecase.go -package usecase -destination usecase_mock.go
//

// Package usecase is a generated GoMock package.
package authusecase

import (
	domain "auth_service/internal/domain/auth"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(ctx context.Context, email string, login string, passwordHash []byte) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, login, passwordHash)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(ctx, email, login, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), ctx, email, login, passwordHash)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepository) GetUserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserByID), ctx, id)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepository) CreateSession(ctx context.Context, s *domain.RefreshSession) (*domain.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, s)
	ret0, _ := ret[0].(*domain.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepositoryMockRecorder) CreateSession(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepository)(nil).CreateSession), ctx, s)
}

// GetActiveByTokenHash mocks base method.
func (m *MockSessionRepository) GetActiveByTokenHash(ctx context.Context, tokenHash []byte) (*domain.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByTokenHash indicates an expected call of GetActiveByTokenHash.
func (mr *MockSessionRepositoryMockRecorder) GetActiveByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).GetActiveByTokenHash), ctx, tokenHash)
}

// ListActiveByUserID mocks base method.
func (m *MockSessionRepository) ListActiveByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActiveByUserID indicates an expected call of ListActiveByUserID.
func (mr *MockSessionRepositoryMockRecorder) ListActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActiveByUserID", reflect.TypeOf((*MockSessionRepository)(nil).ListActiveByUserID), ctx, userID)
}

// RevokeAllByUserID mocks base method.
func (m *MockSessionRepository) RevokeAllByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllByUserID indicates an expected call of RevokeAllByUserID.
func (mr *MockSessionRepositoryMockRecorder) RevokeAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllByUserID", reflect.TypeOf((*MockSessionRepository)(nil).RevokeAllByUserID), ctx, userID)
}

// RevokeByTokenHash mocks base method.
func (m *MockSessionRepository) RevokeByTokenHash(ctx context.Context, tokenHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByTokenHash indicates an expected call of RevokeByTokenHash.
func (mr *MockSessionRepositoryMockRecorder) RevokeByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByTokenHash", reflect.TypeOf((*MockSessionRepository)(nil).RevokeByTokenHash), ctx, tokenHash)
}

// RotateSession mocks base method.
func (m *MockSessionRepository) RotateSession(ctx context.Context, sessionID uuid.UUID, newTokenHash []byte, newExpiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSession", ctx, sessionID, newTokenHash, newExpiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateSession indicates an expected call of RotateSession.
func (mr *MockSessionRepositoryMockRecorder) RotateSession(ctx, sessionID, newTokenHash, newExpiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSession", reflect.TypeOf((*MockSessionRepository)(nil).RotateSession), ctx, sessionID, newTokenHash, newExpiresAt)
}

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockPasswordHasher) Compare(hash []byte, plain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, plain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockPasswordHasherMockRecorder) Compare(hash, plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockPasswordHasher)(nil).Compare), hash, plain)
}

// Hash mocks base method.
func (m *MockPasswordHasher) Hash(plain string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", plain)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordHasherMockRecorder) Hash(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordHasher)(nil).Hash), plain)
}

// MockAccessTokenIssuer is a mock of AccessTokenIssuer interface.
type MockAccessTokenIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenIssuerMockRecorder
	isgomock struct{}
}

// MockAccessTokenIssuerMockRecorder is the mock recorder for MockAccessTokenIssuer.
type MockAccessTokenIssuerMockRecorder struct {
	mock *MockAccessTokenIssuer
}

// NewMockAccessTokenIssuer creates a new mock instance.
func NewMockAccessTokenIssuer(ctrl *gomock.Controller) *MockAccessTokenIssuer {
	mock := &MockAccessTokenIssuer{ctrl: ctrl}
	mock.recorder = &MockAccessTokenIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenIssuer) EXPECT() *MockAccessTokenIssuerMockRecorder {
	return m.recorder
}

// IssueAccessToken mocks base method.
func (m *MockAccessTokenIssuer) IssueAccessToken(userID uuid.UUID, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueAccessToken", userID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueAccessToken indicates an expected call of IssueAccessToken.
func (mr *MockAccessTokenIssuerMockRecorder) IssueAccessToken(userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueAccessToken", reflect.TypeOf((*MockAccessTokenIssuer)(nil).IssueAccessToken), userID, ttl)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
