// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshSession struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	TokenHash         []byte
	ExpiresAt         pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	Ip                string
	UserAgent         string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Login        string
	PasswordHash []byte
	CreatedAt    pgtype.Timestamptz
}
