// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (
    user_id,
    token_hash,
    expires_at,
    absolute_expires_at,
    ip,
    user_agent
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, expires_at, absolute_expires_at, revoked_at, created_at, ip, user_agent
`

type CreateRefreshSessionParams struct {
	UserID            pgtype.UUID
	TokenHash         []byte
	ExpiresAt         pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	Ip                string
	UserAgent         string
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const getRefreshSessionByTokenHash = `-- name: GetRefreshSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, absolute_expires_at, revoked_at, created_at, ip, user_agent
FROM refresh_sessions
WHERE token_hash = $1
    AND revoked_at IS NULL
    AND expires_at > now()
    AND absolute_expires_at > now()
`

func (q *Queries) GetRefreshSessionByTokenHash(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByTokenHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, expires_at, created_at, revoked_at, ip, user_agent
FROM refresh_sessions
WHERE user_id = $1
    AND revoked_at IS NULL
    AND expires_at > now()
    AND absolute_expires_at > now()
ORDER BY created_at DESC
`

type ListActiveSessionsByUserRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	Ip        string
	UserAgent string
}

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSessionsByUserRow
	for rows.Next() {
		var i ListActiveSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Ip,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsByUser = `-- name: RevokeAllSessionsByUser :execrows
UPDATE refresh_sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE refresh_sessions
SET revoked_at = now()
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE refresh_sessions
SET token_hash = $2,
    expires_at = $3
WHERE id = $1
    AND revoked_at IS NULL
    AND expires_at > now()
    AND absolute_expires_at > now()
`

type RotateSessionParams struct {
	ID        pgtype.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession, arg.ID, arg.TokenHash, arg.ExpiresAt)
	return err
}
